spring:
    application:
        name: microservice-client-caller
    freemarker:
        enable: false
    thymeleaf: 
        cache: false
        prefix: classpath:/templates/

error:
    path=/error
    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/
            
server: 
    port: 7777